apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  generation: 1
  labels:
    machineconfigpool.openshift.io/role: sctp
  name: sctp
spec:
  machineConfigSelector:
    matchExpressions:
    - key: machineconfiguration.openshift.io/role
      operator: In
      values:
      - worker
      - sctp-worker
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker-sctp: ""
